# docker-mediadrop
# https://github.com/nmarus/docker-mediadrop
# Nicholas Marus <nmarus@gmail.com>

FROM nmarus/nginx-full
MAINTAINER Nicholas Marus <nmarus@gmail.com>
COPY nginx.conf /etc/nginx/nginx.conf
COPY server.crt /etc/nginx/ssl/server.crt
COPY server.key /etc/nginx/ssl/server.key
